name: "Test Action"

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      with:
        service-account: ${{ secrets.SERVICE_ACCOUNT }}
        project-id: ${{ secrets.PROJECT_ID }}
        config-files: ./app.yml
        delete-previous-versions: true
        no-cache: true
        debug: true